# Generated by Django 3.0.4 on 2020-03-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_user_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
